---

- name: Provision master
  hosts: kubernetes-0
  become: yes
  vars:
    docker_package: "docker-ce=5:19.03.15~3-0~{{ansible_distribution|lower}}-{{ansible_distribution_release}}"
    kubernetes_version: '1.19'
    kubernetes_role: 'master'
    kubernetes_pod_network:
      # # Flannel CNI.
      # cni: 'flannel'
      # cidr: '10.244.0.0/16'
      # Calico CNI.
      cni: 'calico'
      cidr: '10.244.0.0/16'
    kubernetes_apiserver_advertise_address: "0.0.0.0"
    kubernetes_config_cluster_configuration:
      networking:
        podSubnet: "{{ kubernetes_pod_network.cidr }}"
      kubernetesVersion: "{{ kubernetes_version_kubeadm }}"
      apiServer:
        certSANs:
          - "{{ansible_default_ipv4.address}}"
          - "{{ansible_host}}"
      controlPlaneEndpoint: "{{ansible_host}}"
  roles:
    - geerlingguy.docker
    - geerlingguy.kubernetes

- name: Provision node
  hosts: kubernetes-1
  become: yes
  vars:
    docker_package: "docker-ce=5:19.03.15~3-0~{{ansible_distribution|lower}}-{{ansible_distribution_release}}"
    kubernetes_version: '1.19'
    kubernetes_role: 'node'
    kubernetes_pod_network:
      # # Flannel CNI.
      # cni: 'flannel'
      # cidr: '10.244.0.0/16'
      # Calico CNI.
      cni: 'calico'
      cidr: '10.244.0.0/16'
  roles:
    - geerlingguy.docker
    - geerlingguy.kubernetes
